spring:
  application:
    name: inventory

  # Active profile (can be overridden by environment variable)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server Configuration (common for all)
server:
  port: 8080

# Logging (common for all)
logging:
  level:
    com.bussiness.inventory: DEBUG